# Site Settings
title: Graph Neural Networks Blog
description: Deep learning blog focusing on Graph Neural Networks, PyTorch Geometric, and protein function prediction
url: https://AisyluFattakhova.github.io
baseurl: ""
author: Aisylu Fattakhova, Azalia Alisheva

# Build Settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown Processor
markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true

# Include custom CSS and MathJax
sass:
  sass_dir: _sass

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

