# Site Settings
title: Aisyu Fattakhova - Graph Neural Networks Blog
description: Deep learning blog focusing on Graph Neural Networks, PyTorch Geometric, and protein function prediction
url: https://AisyluFattakhova.github.io
baseurl: ""
author: Aisyu Fattakhova

# Build Settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown Processor
markdown: kramdown

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

